#!/bin/bash
set -e

case "$1" in
    configure)
        deb-systemd-invoke enable no-shred.service ||:
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *) 
        echo "ERROR: $0 - unknown argument: $1" >&2
        exit 1
    ;;
esac